### ISSUE TITLE
Allow for multiple tag names to map to the same class

### ISSUE THREAD

**Issue by xrrocha** [xrrocha/yamltag#2]
Currently, tag name can be associated with only one class. For readability reasons its may be convenient to allow the same class to be instantiated via multiple tag names.

A concrete scenario where this is beneficial is when the given class implements multiple interfaces and the developer wants to associate the class with separate tag names for each implemented interface.

``` java
package com.acme.rules;

class Script implements Macher, Transformer {
    private String scriptBody;
    private String languageName = "javascript";
    . . .
}
```

Given the above class, file `yamltag.yaml` would contain:

``` yaml
com.acme.rules.Script
  tagNames: [when, then]
```

A Yamltag-based script could then  look like:

``` yaml
rule:
  matcher: !when [ it.length % 2 == 0 ]
  transformer: !then [ it.toLowerCase() ]

```
